Repository opencb/jsorolla, pull requests merged in 2022-04, with the labels that each got.

#452 TASK-438: Create a Web Component for GenomeBrowser
  src/genome-browser/genome-browser.js
  src/genome-browser/panels/chromosome-panel.js
  src/genome-browser/panels/karyotype-panel.js
  src/genome-browser/panels/tracklist-panel.js
  src/sites/iva/iva-app.js
  src/webcomponents/variant/interpretation/variant-interpreter-browser.js
  src/webcomponents/variant/interpretation/variant-interpreter-review-primary.js
  src/webcomponents/variant/interpretation/variant-interpreter.js
  src/webcomponents/variant/variant-browser.js
  src/webcomponents/visualization/genome-browser.js
Labels: genome-browser, components, variant-browser

#462 TASK-528 - Duplicated features in Gene Overview Track of GenomeBrowser
  src/genome-browser/renderers/feature-renderer.js
  src/genome-browser/renderers/gene-renderer.js
Labels: bug, genome-browser

#460 TASK-476 - Variant Interpreter improvements
  src/webcomponents/variant/interpretation/variant-interpreter-browser-toolbar.js
Labels: improvement, case-interpreter

#477 TASK-576 - Displayed version in IVA should be extracted from package.json
  package.json
  rollup.config.js
  src/sites/iva/iva-app.js
  src/webcomponents/commons/layouts/custom-footer.js
  vite.config.js
Labels: bug

#485 TASK-628 - Chromosome filter in QC section
  src/webcomponents/sample/sample-cancer-variant-stats-plots.js
Labels: bug, case-interpreter

#488 TASK-604 - In REST API app boolean values are checked by default but a false value is sent in the request
  src/webcomponents/api/rest-endpoint.js
Labels: bug

#489 TASK-600 - Review that the detail sections in all browsers
  src/webcomponents/cohort/cohort-detail.js
  src/webcomponents/disease-panel/disease-panel-detail.js
  src/webcomponents/file/opencga-file-detail.js
  src/webcomponents/individual/individual-detail.js
  src/webcomponents/sample/sample-detail.js
Labels: bug

#496 TASK-599 - Improving disease panel detail tab grids: display the number of elements returned in bold
  src/webcomponents/gene/gene-grid.js
Labels: bug

#501 TASK-657 - Disable Search button in the Variant Interpreter and Variant Browser
  src/webcomponents/variant/interpretation/variant-interpreter-browser-template.js
  src/webcomponents/variant/interpretation/variant-interpreter-grid.js
  src/webcomponents/variant/interpretation/variant-interpreter-rearrangement-grid.js
  src/webcomponents/variant/variant-browser-filter.js
  src/webcomponents/variant/variant-browser-grid.js
  src/webcomponents/variant/variant-browser.js
Labels: bug, case-interpreter, variant-browser

#502 TASK-670 - Disable generateKey in OpenCGA client
  src/core/clients/opencga/opencga-parent-class.js
  src/core/clients/rest-client.js
  src/webcomponents/file/file-preview.js
Labels: bug
