Repository opencb/jsorolla, pull requests merged in 2022-09, with the labels that each got.

#629 TASK-1794 - Export query for variant analysis and clinical analysis does not add the output-file-format to the exports, always exporting to VCF
  src/webcomponents/commons/opencga-export.js
Labels: bug, case-interpreter, variant-browser

#630 TASK-1762 - Fix headers in rearrangement browser
  src/webcomponents/variant/interpretation/variant-interpreter-rearrangement-grid.js
Labels: bug, case-interpreter

#632 TASK-1793 - The export query dialog in sample variant browser has a export type as CSV instead VCF
  src/webcomponents/commons/opencga-export.js
Labels: bug, case-interpreter

#634 TASK-1679 - Follow variantCallers configuration in rearrangement variant browsers
  src/webcomponents/variant/interpretation/variant-interpreter-browser-rearrangement.js
  src/webcomponents/variant/interpretation/variant-interpreter-rearrangement-grid.js
Labels: bug, case-interpreter, variant-browser

#635 TASK-1724 - Pop. frequency bar plot does not show values for all populations
  src/webcomponents/variant/annotation/cellbase-population-frequency-grid.js
Labels: bug, case-interpreter

#636 TASK-1870 - Issues when creating new ACMG items in the Review Variant Evidence menu (Sample Variant Browser)
  src/webcomponents/clinical/interpretation/clinical-interpretation-variant-evidence-review.js
Labels: bug, case-interpreter

#637 TASK-1663 - The Download button from the Case Explorer saves files with information of multiple clinical cases but names the downloaded files using the name of a single clinical case
  src/webcomponents/clinical/clinical-analysis-grid.js
Labels: bug, case-interpreter

#640 TASK-1889 - Issue in the samples count in detail section
  src/webcomponents/variant/variant-samples.js
Labels: bug, case-interpreter, variant-browser

#643 TASK-1233 - Fix buttons in Navbar panel of Genome Browser
  src/genome-browser/css/genome-browser.css
  src/genome-browser/panels/navigation-bar.js
Labels: bug, genome-browser

#644 TASK-1659 When sample filter in case portal contains more than one item, removing one from the dropdown menu in the active filter tab, remove all and left the grid unresponsive for new searchs
  src/webcomponents/commons/opencga-active-filters.js
Labels: bug

#646 TASK-1952 - Not able to remove a filter when clicking on the counter badge
  src/webcomponents/commons/opencga-active-filters.js
Labels: bug

#647 TASK-1906 - Details tab Sample (Cohort Browser) shows Error when trying to display information from the /samples/search endpoint
  src/webcomponents/cohort/cohort-browser.js
Labels: bug

#650 TASK-1918 - Job overview view does not parse correctly the Input parameters for `analysis/variant/sample/stats/run` and leaves it as [object Object]
  src/webcomponents/job/job-view.js
Labels: bug

#621 TASK-1536 - Wrong disposition of information when exporting variants in TSV format
  .eslintrc.json
  src/webcomponents/variant/interpretation/variant-interpreter-grid.js
  src/webcomponents/variant/variant-browser-grid.js
  src/webcomponents/variant/variant-utils.js
Labels: bug

#651 TASK-1875 - IVA Sample browser shows a "Type error" when some attributes have undefined values
  src/webcomponents/sample/sample-grid.js
Labels: bug

#652 TASK-1939 - IVA REST-API tool for families create does not pass the family members to the REST call
  src/webcomponents/api/rest-endpoint.js
Labels: bug, REST-API

#653 TASK-1991 - The population frequencies of the 1000 Genomes study are not being displayed as expected in the Variant Browser
  src/webcomponents/variant/annotation/cellbase-population-frequency-grid.js
Labels: bug, variant-browser

#654 TASK-2004 - UI issues in active filters menu
  src/webcomponents/commons/opencga-active-filters.js
  src/webcomponents/variant/interpretation/variant-interpreter-browser-cancer.js
  src/webcomponents/variant/interpretation/variant-interpreter-browser-cnv.js
  src/webcomponents/variant/interpretation/variant-interpreter-browser-rd.js
  src/webcomponents/variant/interpretation/variant-interpreter-browser-rearrangement.js
Labels: bug

#658 TASK-2082 - Unable to filter by disorders when disorders.name is empty
  src/webcomponents/commons/filters/catalog-distinct-autocomplete.js
  src/webcomponents/commons/opencga-browser-filter.js
  src/webcomponents/file/file-filter.js
Labels: bug

#660 TASK-2053 - Notifications are not displaying results events
  src/core/notification-manager.js
Labels: bug

#662 TASK-2093 - Link to sequenceontology not working
  src/core/bioinfo/bioinfo-utils.js
  src/webcomponents/variant/interpretation/variant-interpreter-grid-formatter.js
  src/webcomponents/variant/variant-grid-formatter.js
Labels: bug, variant-browser

#663 TASK-2130 - Sample Genotypes filter is not applying Mode of Inheritance
  src/webcomponents/variant/family-genotype-filter.js
Labels: bug, variant-browser

#666 TASK-2116 - Job view displays output files without names
  src/webcomponents/job/job-view.js
Labels: bug

#667 TASK-2078 - Style issues in active filters buttons
  src/webcomponents/commons/opencga-active-filters.js
Labels: bug
