Repository opencb/jsorolla, pull requests merged in 2022-08, with the labels that each got.

#606 TASK-1468 - Individual Browser phenotype and disease filters: search does not restring results
  src/webcomponents/commons/filters/catalog-distinct-autocomplete.js
  src/webcomponents/commons/forms/select-token-filter.js
Labels: bug

#607 TASK-1400 - Export Query is not working in Sample Variant Browser
  src/webcomponents/commons/opencga-export.js
Labels: bug, case-interpreter

#611 TASK-1552 - Flags are not correctly displayed in clinical analysis view
  src/webcomponents/clinical/clinical-analysis-view.js
Labels: bug, case-interpreter

#614 TASK-1620 - 'Assigned To' field is empty when exporting clinical analysis
  src/webcomponents/clinical/clinical-analysis-grid.js
Labels: bug, case-interpreter

#608 TASK-1458 - Error when filtering by type in rearrangement browser
  src/webcomponents/commons/filters/variant-file-info-filter.js
Labels: bug, case-interpreter

#609 TASK-1590 - "Assign to" value is missing in case overview tabs
  src/webcomponents/clinical/clinical-analysis-view.js
Labels: bug, case-interpreter

#613 TASK-1560 - The dialog buttons inside the action buttons in Sample Variant Browser performs an action even if they are disabled
  src/webcomponents/variant/interpretation/variant-interpreter-browser-toolbar.js
Labels: bug

#616 TASK-1622 - Run button is missing in Somatic and Germline Variant stats
  src/webcomponents/sample/sample-variant-stats-browser.js
Labels: bug

#612 TASK-1374 - Fix custom clinical interpretation fields in variant grid
  src/webcomponents/variant/interpretation/variant-interpreter-grid.js
  src/webcomponents/variant/interpretation/variant-interpreter-rearrangement-grid.js
Labels: bug, case-interpreter

#622 TASK-1461 - Settings in variant tables in report
  src/webcomponents/commons/view/detail-tabs.js
  src/webcomponents/variant/interpretation/case-steiner-report.js
  src/webcomponents/variant/interpretation/variant-interpreter-rearrangement-grid.js
Labels: bug, case-interpreter

#623 TASK-1243 - Rename columns
  src/webcomponents/variant/interpretation/variant-interpreter-grid.js
Labels: bug, case-interpreter

#624 TASK-1501 - GB link is still visible in the Actions menu after disabling GB in the interpretation settings
  src/webcomponents/variant/interpretation/variant-interpreter-browser-template.js
  src/webcomponents/variant/interpretation/variant-interpreter-browser.js
  src/webcomponents/variant/interpretation/variant-interpreter-grid.js
  src/webcomponents/variant/interpretation/variant-interpreter-review-primary.js
Labels: bug, genome-browser, case-interpreter

#625 TASK-1691 - Limit the width of the discussion column in the Reported Cases section of SVB
  src/webcomponents/variant/variant-grid-formatter.js
Labels: bug, case-interpreter

#627 TASK-1661 - File browser hide column directory does not work.
  src/webcomponents/file/file-grid.js
Labels: bug
