Repository opencb/jsorolla, pull requests merged in 2022-07, with the labels that each got.

#568 TASK-1099 - Clicking on "+" must select the variant
  src/webcomponents/variant/interpretation/variant-interpreter-grid.js
  src/webcomponents/variant/variant-browser-grid.js
Labels: bug, case-interpreter

#569 TASK-1098 - Include small deletions and insertions count plot in report
  src/webcomponents/variant/interpretation/case-steiner-report.js
Labels: improvement, case-interpreter

#570 TASK-1107 - Add variant link to Genome Browser
  src/webcomponents/commons/view/detail-tabs.js
  src/webcomponents/variant/interpretation/variant-interpreter-browser.js
  src/webcomponents/variant/interpretation/variant-interpreter-grid.js
Labels: improvement, genome-browser, case-interpreter

#573 TASK-1259 - CatalogException Cannot see stderr log file of job with status 'QUEUED'.
  src/webcomponents/job/opencga-job-detail-log.js
Labels: bug

#574 TASK-1268 - IVA: No valid token : null
  src/sites/api/api-app.js
  src/sites/iva/iva-app.js
Labels: bug

#572 TASK-1104 - Split screen on genome browser
  src/genome-browser/genome-browser.js
  src/genome-browser/panels/navigation-bar.js
  src/webcomponents/commons/view/detail-tabs.js
  src/webcomponents/variant/interpretation/variant-interpreter-browser-rearrangement.js
  src/webcomponents/variant/interpretation/variant-interpreter-browser.js
  src/webcomponents/variant/interpretation/variant-interpreter-detail.js
  src/webcomponents/visualization/split-genome-browser.js
Labels: improvement, genome-browser, case-interpreter

#581 TASK-1360 - Typo in Job Browser Logs
  src/webcomponents/job/opencga-job-detail-log.js
Labels: bug

#578 TASK-1228 - Panel container is still visible after disabling it in the configuration of Genome Browser.
  src/genome-browser/genome-browser.js
Labels: bug, genome-browser

#579 TASK-974 - Action dropdown in variant grid component in the last rows becomes hidden when it is beyond the table limits
  src/webcomponents/variant/interpretation/variant-interpreter-grid.js
Labels: bug, case-interpreter

#577 TASK-1207 - Filter section is not displayed in case portal view in customers with IVA 2.4.x
  src/core/utilsNew.js
  src/webcomponents/commons/opencga-browser-filter.js
Labels: bug, UI/UX

#580 TASK-1269 - VB deleterious filters ranges need to be limited in the score input area (SIFT, Polyphen and CADD)
  src/webcomponents/commons/filters/cadd-filter.js
  src/webcomponents/commons/filters/protein-substitution-score-filter.js
Labels: bug

#582 TASK-1234 - Icons in Genome Browser navbar buttons are not displayed
  rollup.config.js
  src/genome-browser/css/genome-browser.css
  src/genome-browser/demo/genome-browser-opencga.html
  src/genome-browser/demo/genome-browser.html
  src/genome-browser/img/icon-chromosome.png
  src/genome-browser/img/icon-karyotype.png
  src/genome-browser/img/icon-region.png
  src/genome-browser/img/track-resize.png
  src/sites/iva/index.html
Labels: bug, genome-browser

#583 TASK-1231 - Variant Track must display all samples without scrolling
  src/genome-browser/tracks/opencga-variant-track.js
  src/webcomponents/variant/interpretation/variant-interpreter-browser.js
Labels: bug, genome-browser

#584 TASK-1364 - File Explorer does not clear the file info section when opening a folder
  src/sites/iva/iva-app.js
  src/webcomponents/file/file-manager.js
Labels: bug

#575 TASK-1263 - Job logs are not displayed while the job is running
  src/sites/iva/iva-app.js
  src/webcomponents/job/job-browser.js
  src/webcomponents/job/job-detail-log.js
  src/webcomponents/job/job-detail.js
  src/webcomponents/job/job-view.js
  src/webcomponents/job/opencga-job-detail-log.js
Labels: bug

#585 TASK-1256 - The warning about new changes not been saved should not be shown before starting to edit the "create case" form.
  src/webcomponents/clinical/clinical-analysis-create.js
  src/webcomponents/commons/forms/data-form.js
Labels: bug

#586 TASK-1444 - Detailed section in Genome Browser is not visible
  src/genome-browser/genome-browser.js
Labels: bug, genome-browser

#587 TASK-1439 - Changing a tab in variant interpreter details hides all interpreter browsers
  src/webcomponents/commons/view/detail-tabs.js
Labels: bug, case-interpreter

#588 TASK-1417 - Missing search button in QC
  src/webcomponents/sample/sample-cancer-variant-stats-browser.js
Labels: bug, case-interpreter

#589 TASK-1419 - Export modal in Variant Browser is still using ripple buttons
  src/webcomponents/commons/opencga-export.js
  styles/css/global.css
Labels: bug, case-interpreter, variant-browser

#590 TASK-1416 - Fill custom filtering section in report
  src/webcomponents/variant/interpretation/case-steiner-report.js
Labels: bug, case-interpreter

#594 TASK-1502 - Individual Browser phenotype and disease filters: search does not restring results
  src/webcomponents/commons/filters/disorder-autocomplete.js
  src/webcomponents/commons/filters/phenotype-name-autocomplete.js
Labels: bug

#595 TASK-1465 - Clear filter action clears disabled filters too
  src/webcomponents/variant/interpretation/variant-interpreter-browser-template.js
Labels: bug, case-interpreter

#596 TASK-1244 - Missing export rearrangement variants
  src/core/utilsNew.js
  src/webcomponents/commons/opencga-export.js
  src/webcomponents/variant/interpretation/variant-interpreter-browser-rearrangement.js
  src/webcomponents/variant/interpretation/variant-interpreter-grid.js
  src/webcomponents/variant/interpretation/variant-interpreter-rearrangement-grid.js
Labels: bug, case-interpreter

#597 TASK-1533 - Wrong filter name when filtering by sample ID
  src/webcomponents/commons/opencga-active-filters.js
  src/webcomponents/variant/interpretation/variant-interpreter-browser-cancer.js
  src/webcomponents/variant/interpretation/variant-interpreter-browser-cnv.js
  src/webcomponents/variant/interpretation/variant-interpreter-browser-rd.js
Labels: bug

#598 TASK-1541 - Show author and date in variant comments
  src/webcomponents/clinical/interpretation/clinical-interpretation-variant-review.js
Labels: bug, case-interpreter

#599 TASK-1526 - In individual browser disorders are not correctly rendered
  src/webcomponents/disease-panel/disease-panel-summary.js
  src/webcomponents/family/family-view.js
  src/webcomponents/individual/individual-view.js
Labels: bug

#600 TASK-1473 - Review variant comments don't show who and when were written
  src/webcomponents/clinical/interpretation/clinical-interpretation-variant-review.js
Labels: bug, case-interpreter

#603 TASK-1531 - Show Author and Date in Discussion Box.
  src/webcomponents/clinical/clinical-analysis-comment-editor.js
  src/webcomponents/clinical/clinical-analysis-review.js
  src/webcomponents/clinical/interpretation/clinical-interpretation-variant-evidence-review.js
  src/webcomponents/clinical/interpretation/clinical-interpretation-variant-review.js
  src/webcomponents/commons/forms/form-utils.js
Labels: bug, case-interpreter

#602 TASK-1522 - File browser search filter by file or directory does not work
  src/webcomponents/commons/filters/catalog-search-autocomplete.js
  src/webcomponents/commons/forms/select-token-filter.js
  src/webcomponents/commons/opencga-browser-filter.js
Labels: bug

#604 TASK-1094 - Filter by X-linked segregation mode returns variants outside chrX
  src/webcomponents/variant/family-genotype-filter.js
Labels: bug, case-interpreter

#605 TASK-1534 - Cannot unselect variants from Interpretation Review
  src/webcomponents/variant/interpretation/variant-interpreter-grid.js
  src/webcomponents/variant/interpretation/variant-interpreter-review-primary.js
Labels: bug, case-interpreter
